Numpy 학습목표
- 배열의 데이터타입 (인공지능에서 사용하게 될 데이터타입)
- 생성, 다루는 방법
- 통계에 관련된 함수를 지원
- 벡터화 연산, 행렬 연산
- 파이썬의 리스트(다양한 요소의 타입들 가질 수 있음)와는 다르다(넘파이는 요소의 타입들이 같아야 함)
- 원소의 개수를 변경할 수 없다(resizing x)
- 배열의 차원, 크기, 타입(배열 안에 들어있는 요소의 타입. 변수타입 의미 아님!)(ndim, shape, dtype)

In [87]:
import numpy as np
import pandas as pd   # 항상 np와 함께 import 해줌

- 배열을 생성하는 함수 : array(), arange(), reshape() 

In [88]:
lst = [1,2,3,4,5]
print('type - ' , type(lst))

ary = np.array(lst) 
print('type - ' , type(ary))
print('shape - ', ary.shape)   
print('ndim - ', ary.ndim)   # => 1 : 열만 있는 1차원
print('dtype - ', ary.dtype)

type -  <class 'list'>
type -  <class 'numpy.ndarray'>
shape -  (5,)
ndim -  1
dtype -  int32


In [89]:
# 배열에 대한 정보를 쉽게 확인하기 위하여 함수를 만들어두면 편리하다
def aryInfo(ary) :
    print('type - ' , type(ary))
    print('shape - ', ary.shape)   
    print('ndim - ', ary.ndim)
    print('dtype - ', ary.dtype)
    print()
    print()
    print('data - ')
    print(ary)     # list 와의 차이점 : ',' 없음. 배열로 보면 됨!

In [90]:
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (5,)
ndim -  1
dtype -  int32


data - 
[1 2 3 4 5]


In [91]:
# 각 요소의 값에 제곱하기 (1.반복구문 2. list comprehention)
lst = [1,2,3,4,5,6,7,8,9]
print(lst * 2)  # 반복 구문임

# 벡터화 연산
ary = np.array(lst)
print(ary * 2)   

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 2  4  6  8 10 12 14 16 18]


In [92]:
print('산술연산 - ')
# 배열의 shape 이 동일하면 ...
ary01 = np.array([1,2,3,4,5])
ary02 = np.array([10,20,30,40,50])

print(ary01 + ary02)
# 반복 구문을 사용해서 더하지 않고도 연산이 가능

산술연산 - 
[11 22 33 44 55]


In [93]:
print('비교연산 - ')
print(ary01 == 2)

booleanMasking = (ary01 == 2 )  # array 가 2인 곳을 True 로 만듦
print(booleanMasking)

print('indexing - ', ary01[0])
print('indexing - ', ary01[1])
print('slicing - ', ary01[0:3])
print('boolean indexing - ', ary01[booleanMasking]) # True인 번지의 인덱싱 값만 출력해줌

비교연산 - 
[False  True False False False]
[False  True False False False]
indexing -  1
indexing -  2
slicing -  [1 2 3]
boolean indexing -  [2]


In [94]:
print('논리연산 - ')

print( ary02 > 10)
print()
print((ary01 == 2))
print((ary02 > 10))
print((ary01 == 2) & (ary02 > 10))   # and 연산 = 논리곱
print((ary01 == 2) | (ary02 > 10))   # or 연산 = 논리합

논리연산 - 
[False  True  True  True  True]

[False  True False False False]
[False  True  True  True  True]
[False  True False False False]
[False  True  True  True  True]


- 2차원 배열(행렬, matrix) : list of list



In [95]:
print('2*3 배열을 생성하고 싶다면?')

lst = [[1,2,3],[4,5,6]] # 2행 3열
print(lst[0])   # 첫번째 열 출력 => list 형식
print(lst[0][0])   # list의 [0] 값

for row in lst :
    for rIdx, row in enumerate(lst) :
        for cIdx, col in enumerate(row) :
            print(row, end='\t')
            print(col, end='\t')
    print()

2*3 배열을 생성하고 싶다면?
[1, 2, 3]
1
[1, 2, 3]	1	[1, 2, 3]	2	[1, 2, 3]	3	[4, 5, 6]	4	[4, 5, 6]	5	[4, 5, 6]	6	
[1, 2, 3]	1	[1, 2, 3]	2	[1, 2, 3]	3	[4, 5, 6]	4	[4, 5, 6]	5	[4, 5, 6]	6	


In [96]:
ary = np.array(lst)
aryInfo(ary)
print()
print(len(ary))
print(len(ary[0]))

type -  <class 'numpy.ndarray'>
shape -  (2, 3)
ndim -  2
dtype -  int32


data - 
[[1 2 3]
 [4 5 6]]

2
3


In [118]:
print('2 * 3 * 4 배열을 생성하고 싶다면?')
        # 3*4 짜리 2차원 배열이 2개 있는 것 => 3차원으로 봄
    # 요소 값 입력하기
lst = [ [ [1,2,3,4],[5,6,7,8],[9,10,11,12] ] , 
       [ [13,14,15,16],[17,18,19,20],[21,22,23,24] ] ]

ary = np.array(lst)   # 배열 만들기
aryInfo(ary)
print()
print(len(ary))
print(len(ary[0]))
print(len(ary[1]))

2 * 3 * 4 배열을 생성하고 싶다면?
type -  <class 'numpy.ndarray'>
shape -  (2, 3, 4)
ndim -  3
dtype -  int32


data - 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

2
3
3


- astype() : 요소의 타입을 변경할 때
- 1차원, 2차원 적용이 가능


In [105]:
aryInfo(ary.astype(np.float64))   # dtype을 float64(타입)로 변경

type -  <class 'numpy.ndarray'>
shape -  (2, 3, 4)
ndim -  3
dtype -  float64


data - 
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


- 배열에서 인덱싱, 슬라이싱
- 차이점 : boolean indexing이 있음

In [117]:
print('[행,열]')
ary = np.array( [ [1,2,3,4] , [5,6,7,8] ] )
aryInfo(ary)
print()
print('첫번째 행의 첫번째 열 값을 추출 - ', ary[0,0], ary[0][0])
print('두번째 행의 첫번째 열 값을 추출 - ', ary[1,0], ary[1][0])
print('마지막 행의 마지막 열 값을 추출 - ', ary[-1,-1], ary[-1][-1])
print('첫번째 행의 전체 열 값을 추출 - ', ary[0, : ],  ary[0][:])   # 열에 대한 슬라이싱 => 전체 가져오기
print('두번째 행의 전체 열 값을 추출 - ', ary[1, : ], ary[1][:])
print('두번째 행의 두번째 열부터 끝까지의 값을 추출 - ', ary[1, 1:], ary[1][1:])

[행,열]
type -  <class 'numpy.ndarray'>
shape -  (2, 4)
ndim -  2
dtype -  int32


data - 
[[1 2 3 4]
 [5 6 7 8]]

첫번째 행의 첫번째 열 값을 추출 -  1 1
두번째 행의 첫번째 열 값을 추출 -  5 5
마지막 행의 마지막 열 값을 추출 -  8 8
첫번째 행의 전체 열 값을 추출 -  [1 2 3 4] [1 2 3 4]
두번째 행의 전체 열 값을 추출 -  [5 6 7 8] [5 6 7 8]
두번째 행의 두번째 열부터 끝까지의 값을 추출 -  [6 7 8] [6 7 8]


In [130]:
print('fancy indexing - 정수배열 인덱싱(첨자), 불린 배열 인덱싱(T/F)')
print()
ary = np.array([0,1,2,3,4,5,6,7,8,9])
# aryInfo(ary)
print()
print('Q. 짝수의 원소(2의 배수)만 출력한다면 - ')
# print('dir - ', dir(ary))

# for data in ary :
#     if data % 2 == 0 :
#         print(data)

print('boolean 인덱싱 - ', ary[ ary % 2 == 0] )

evenIdx = np.array([0,2,4,6,8])
print('정수 배열 인덱싱 - ', ary[evenIdx])

fancy indexing - 정수배열 인덱싱(첨자), 불린 배열 인덱싱(T/F)


Q. 짝수의 원소(2의 배수)만 출력한다면 - 
boolean 인덱싱 -  [0 2 4 6 8]
정수 배열 인덱싱 -  [0 2 4 6 8]


#### Quiz.
- 3의 배수만 출력
- 4로 나누어 1이 남는 값들만 출력
- 3의 배수이고 4로 나누어 1이 남는 값들만 출력

In [138]:
# arange() 로 범위를 주고 그 범위에 맞는 배열 만들 수 있다
ary = np.arange(1,21)
# aryInfo(ary)

print('1번. ',ary[ ary % 3 == 0])
print('2번. ',ary[ ary % 4 == 1])
print('1번. ',ary[ (ary % 3 == 0) & (ary % 4 == 1)])

1번.  [ 3  6  9 12 15 18]
2번.  [ 1  5  9 13 17]
1번.  [9]


- reshape() : 배열을 변형 시켜주는 함수

In [184]:
# np.arange(1,13)  # 1차원 배열
ary = np.arange(1,13).reshape(-1,4)  # 2차원 배열 만들고 싶을 때, 변형 함수 사용
aryInfo(ary)
print()
colIdx = [0,3]
print('정수 배열 인덱싱을 이용해서 모든 행의 0,3 열 값 출력 >>> ', ary[ : , colIdx])
boolIdx = [True, False, False, True]
print('불린 배열 인덱싱을 이용해서 모든 행의 0,3 열 값 출력 >>> ', ary[ : , boolIdx])
print('5 값 추출', ary[1,0], type(ary[1,0]))
print('[2 10] 값 추출 >>> ', ary[[0, 2], 1])  # 2차원 배열이 리턴 됨
print('[2] [10] 값 추출 >>> ', ary[[0,2], 1:2])
print('[1 3] [9 11] 값 추출 >>> ')

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
ndim -  2
dtype -  int32


data - 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

정수 배열 인덱싱을 이용해서 모든 행의 0,3 열 값 출력 >>>  [[ 1  4]
 [ 5  8]
 [ 9 12]]
불린 배열 인덱싱을 이용해서 모든 행의 0,3 열 값 출력 >>>  [[ 1  4]
 [ 5  8]
 [ 9 12]]
5 값 추출 5 <class 'numpy.int32'>
[2 10] 값 추출 >>>  [ 2 10]
[2] [10] 값 추출 >>>  [[ 2]
 [10]]
[1 3] [9 11] 값 추출 >>> 
