In [56]:
import numpy as np
import pandas as pd   # 항상 np와 함께 import 해줌

In [ ]:
# 배열에 대한 정보를 쉽게 확인하기 위하여 함수를 만들어두면 편리하다
def aryInfo(ary) :
    print('type - ' , type(ary))
    print('shape - ', ary.shape)   
    print('ndim - ', ary.ndim)
    print('dtype - ', ary.dtype)
    print()
    print()
    print('data - ')
    print(ary)     # list 와의 차이점 : ',' 없음. 배열로 보면 됨!

- 전치행렬(transpose matirx)
- T

In [301]:
ary = np.arange(1,7).reshape(2,3)
aryInfo(ary)
print()
transposeAry = ary.T 
aryInfo(transposeAry) 

type -  <class 'numpy.ndarray'>
shape -  (2, 3)
ndim -  2
dtype -  int32


data - 
[[1 2 3]
 [4 5 6]]

type -  <class 'numpy.ndarray'>
shape -  (3, 2)
ndim -  2
dtype -  int32


data - 
[[1 4]
 [2 5]
 [3 6]]


In [302]:
print('1차원 배열에 대한 전치행렬이 필요할까요? ') 
print('정답 : 필요하다 ')
print('이유는 : 함수의 인자로 배열 넘길때 타입이 맞아야 하므로') 
ary = np.arange(1 , 7)
aryInfo(ary)

transposeAry = ary.reshape(1,6).T
aryInfo(transposeAry)

1차원 배열에 대한 전치행렬이 필요할까요? 
정답 : 필요하다 
이유는 : 함수의 인자로 배열 넘길때 타입이 맞아야 하므로
type -  <class 'numpy.ndarray'>
shape -  (6,)
ndim -  1
dtype -  int32


data - 
[1 2 3 4 5 6]
type -  <class 'numpy.ndarray'>
shape -  (6, 1)
ndim -  2
dtype -  int32


data - 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


flatten : 다차원 배열을 1차원으로 바꿀때

In [303]:
aryInfo(transposeAry.flatten() )

type -  <class 'numpy.ndarray'>
shape -  (6,)
ndim -  1
dtype -  int32


data - 
[1 2 3 4 5 6]


- 주의사항) 차원에 대한 주의가 필요함

In [304]:
ary = np.arange(10)
aryInfo(ary)

print()

print( ary.reshape(1, 10))
print( ary.reshape(10, 1))

print()
print('차원의 변경이 아니라 차원증가 - np.newaxis')
print()
print( ary[ np.newaxis , : ] )
print( ary[ : ,  np.newaxis ] )

type -  <class 'numpy.ndarray'>
shape -  (10,)
ndim -  1
dtype -  int32


data - 
[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

차원의 변경이 아니라 차원증가 - np.newaxis

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


- 배열 연결

In [305]:
print('hstack() - 행의갯수가 동일한 두개의 배열을 연결 - ') 
ary01 = np.ones((3,4))
ary02 = np.zeros((3,4))

hstack() - 행의갯수가 동일한 두개의 배열을 연결 - 


In [306]:
aryInfo(ary01)
print()
aryInfo(ary02)
print()
print('hstack - ')
print( np.hstack([ary01, ary02]))

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
ndim -  2
dtype -  float64


data - 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
ndim -  2
dtype -  float64


data - 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

hstack - 
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]


In [307]:
print('vstack() - 열의갯수가 동일한 두개의 배열을 연결 - ') 
ary01 = np.ones((3,4))
ary02 = np.zeros((3,4))

vstack() - 열의갯수가 동일한 두개의 배열을 연결 - 


In [308]:
print('vstack - ')
print( np.vstack([ary01, ary02]))

vstack - 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [309]:
print(ary01)
print()
print(ary02)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [310]:
print('stack - 사용자가 지정한 축(x,y)')
print('축 axis = 0 , axis = 1')
print('shape axis=0 - 2*3*4 , axis=1 3*2*4 ')
ary01 = np.ones((3,4))
ary02 = np.zeros((3,4))

aryInfo( np.stack([ary01, ary02] , axis =1))

stack - 사용자가 지정한 축(x,y)
축 axis = 0 , axis = 1
shape axis=0 - 2*3*4 , axis=1 3*2*4 
type -  <class 'numpy.ndarray'>
shape -  (3, 2, 4)
ndim -  3
dtype -  float64


data - 
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


In [62]:
print('tile() - 동일한 배열을 반복하여 연결')
ary = np.arange(1,7).reshape(-1,3)
# np.tile(ary, 3)
np.tile(ary, (3,3))

tile() - 동일한 배열을 반복하여 연결


array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [91]:
# 위 결과가 나올 수 있도록 함수를 이용하여 작성해 보세요~~~
# 붙이기 : hstack(), arange(), vstack() 붙이기,  tile() 반복
#
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

In [117]:
ary01 = np.zeros((3,3))
ary02 = np.ones((3,2))
ary12 = np.hstack([ary01, ary02])
ary03 = np.arange(10,160,10).reshape(3,5)
ary123 = np.vstack([ary12, ary03])
answerAry = np.tile(ary123, (2,1))

In [119]:
# print(ary123)
print(answerAry)   # 숫자 뒤의 '.''은 실수형이라는 의미


[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


#### 데이터 삭제
- delete()
- 기준 axis = 0(행) , axis = 1(열)
- 기준을 정의하지 않는다면 1차원으로 변경되어 삭제시킴
- 리턴이 있다(원본배열에 적용하는 것이 아니라 변경된 새로운 리턴)
  => 따라서 변경된 값을 사용하기 위해서는 새로운 변수에 저장해주어야 함

In [312]:
ary = np.random.randint(0, 10, (3,4))
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
ndim -  2
dtype -  int32


data - 
[[0 4 2 0]
 [9 9 4 6]
 [7 8 3 8]]


In [313]:
# np.delete(ary, 0, axis = 0)

NewAry = np.delete(ary, 1, axis = 0 )
# 삭제 할 배열 / 삭제할 값 / 축의 방향(0 or 1)
NewAry

array([[0, 4, 2, 0],
       [7, 8, 3, 8]])

In [314]:
# 축의 방향 지정 하지 않을 경우 1차원으로 변경시키고, [1]의 값을 삭제시킴
np.delete(ary,1)   #  '3' 이 지워진 것 볼 수 있다

array([0, 2, 0, 9, 9, 4, 6, 7, 8, 3, 8])

#### 통계함수 (차원 축소 함수 = demension reduction)
- 기술적통계(min, max, sum, mean, median, std, var, etc...)
- all, any
- 중요) argmin, argmax : 인덱스를 리턴한다


In [315]:
ary = np.array([1,2,3,4,5,6,7,8,9,10])
print('data - ', ary.shape , ary.ndim, ary.dtype)
print('sum  - ', np.sum(ary))
print('mean  - ', np.mean(ary))     # 평균
print('median  - ', np.median(ary))   # 중위수
print('max  - ', np.max(ary))    # 리턴 : 인덱스 ***
print('min  - ', np.min(ary))
print('var  - ', np.var(ary))    # 분산
print('std  - ', np.std(ary))     # 표준편차
print('quartile - ', np.percentile(ary, 0))
print('quartile - ', np.percentile(ary, 25)) # 1사분위
print('quartile - ', np.percentile(ary, 50)) # 2사분위
print('quartile - ', np.percentile(ary, 75)) 
print('quartile - ', np.percentile(ary, 100)) 

data -  (10,) 1 int32
sum  -  55
mean  -  5.5
median  -  5.5
max  -  10
min  -  1
var  -  8.25
std  -  2.8722813232690143
quartile -  1.0
quartile -  3.25
quartile -  5.5
quartile -  7.75
quartile -  10.0


In [316]:
print('argmin - ' , ary[ np.argmin(ary) ])  # 최소값의 index 값
print('argmax - ' , ary[ np.argmax(ary) ])
print()
print('any - ', np.any([True, False, True]))  # 하나라도 True 값 가지면 => True
print('all - ', np.all([True, False, True]))  # 모두 True 값 가지면 => True

argmin -  1
argmax -  10

any -  True
all -  False


In [317]:
ary = np.arange(1, 21).reshape(4,-1)
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (4, 5)
ndim -  2
dtype -  int32


data - 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [318]:
print('2차원 배열에서 자원축소함수를 적용하기 위해서는 axis 설정이 중요!')
print('0 : 열 , 1 : 행')
print('sum - ', np.sum(ary) , type(np.sum(ary)))
print('sum - ', np.sum(ary, axis=0) , type(np.sum(ary, axis=0)))
print('sum - ', np.sum(ary, axis=1) , type(np.sum(ary, axis=1)))

2차원 배열에서 자원축소함수를 적용하기 위해서는 axis 설정이 중요!
0 : 열 , 1 : 행
sum -  210 <class 'numpy.int32'>
sum -  [34 38 42 46 50] <class 'numpy.ndarray'>
sum -  [15 40 65 90] <class 'numpy.ndarray'>


Quiz


In [319]:
ary = np.random.randint( 0, 100000, (5,6))
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (5, 6)
ndim -  2
dtype -  int32


data - 
[[28841 56277 83643 44548 61018 17825]
 [30150 19305 41603 13474 63174 97246]
 [30259 69345 76423 18364 96371 36227]
 [69841 43011 26783  4241 89268 35514]
 [49484 82210 64117 77025  6083 61325]]


In [320]:
print('전체의 최대값 - ', np.max(ary))
print('행 합 - ', np.sum(ary, axis=1), np.sum(ary, axis=1).shape) # (열개수=5,행개수=1)
sumAry = np.sum(ary , axis = 1).reshape(5,-1)
print('행 합을 열로 추가 - ')
print(np.hstack([ary, sumAry]))

# print( [ ary[0].sum() for idx in range(ary.shape[0])] ) => list 형식이므로 [,,,,]
print( np.array([ ary[idx].sum() for idx in range(ary.shape[0])]) )  # => 배열로 바꿔주기

print()
print('각 행의 최대값 - ', np.max(ary, axis = 1))
maxAry = np.max(ary, axis = 1).reshape(5,-1)
print('각 행의 최대값 열로 추가- ', np.hstack( [ary, maxAry]) )
print('각 열의 평균 - ', np.mean(ary, axis = 0))   
meanAry = np.mean(ary, axis = 0).reshape(1,-1)
print('각 열의 평균 행으로 추가 - ', np.vstack( [ary, meanAry]))
print()
print('각 열의 최소값 - ', np.min(ary , axis = 0))

전체의 최대값 -  97246
행 합 -  [292152 264952 326989 268658 340244] (5,)
행 합을 열로 추가 - 
[[ 28841  56277  83643  44548  61018  17825 292152]
 [ 30150  19305  41603  13474  63174  97246 264952]
 [ 30259  69345  76423  18364  96371  36227 326989]
 [ 69841  43011  26783   4241  89268  35514 268658]
 [ 49484  82210  64117  77025   6083  61325 340244]]
[292152 264952 326989 268658 340244]

각 행의 최대값 -  [83643 97246 96371 89268 82210]
각 행의 최대값 열로 추가-  [[28841 56277 83643 44548 61018 17825 83643]
 [30150 19305 41603 13474 63174 97246 97246]
 [30259 69345 76423 18364 96371 36227 96371]
 [69841 43011 26783  4241 89268 35514 89268]
 [49484 82210 64117 77025  6083 61325 82210]]
각 열의 평균 -  [41715.  54029.6 58513.8 31530.4 63182.8 49627.4]
각 열의 평균 행으로 추가 -  [[28841.  56277.  83643.  44548.  61018.  17825. ]
 [30150.  19305.  41603.  13474.  63174.  97246. ]
 [30259.  69345.  76423.  18364.  96371.  36227. ]
 [69841.  43011.  26783.   4241.  89268.  35514. ]
 [49484.  82210.  64117.  77025.   6083.  61325. ]


sorting
- np.sort() : 원본에 대한 변경 X(inplace = False)
- any.sort() : 원본에 대한 변경 O(inplace = True)

In [332]:
ary = np.arange(10)   # 10자리 배열 생성
print(ary)
print()
np.random.shuffle(ary)    # random 으로 shuffle 해줌
print('shuffle 결과 : ' , ary)  # ----------------------------
print('np.sort - ')
# print(np.sort(ary))   # sorting(정렬) 했지만 원본에 반영되지 않았으므로 사용하려면 새 변수에 저장 필요
newAry = np.sort(ary)  # 변수에 넣어주기
print('newAry - ', newAry) # sorting 된 상태로 출력됨!!

print('ary - ', ary) # 원본 출력 (확인용) => 원래의 shuffle된 순서로 출력됨

print('desc(역순) - ')
newAry = np.sort(ary)[::-1]
print(newAry)

[0 1 2 3 4 5 6 7 8 9]

shuffle 결과 :  [9 0 2 1 8 6 7 4 3 5]
np.sort - 
newAry -  [0 1 2 3 4 5 6 7 8 9]
ary -  [9 0 2 1 8 6 7 4 3 5]
desc(역순) - 
[9 8 7 6 5 4 3 2 1 0]


In [322]:
print('행렬에 대한 정렬 - ')
ary = np.random.randint(1,17, (4,4))
print(ary)

행렬에 대한 정렬 - 
[[16 11 15 15]
 [ 8 15  5  1]
 [12 16 10  5]
 [ 3 15  8  1]]


In [323]:
# 행/열에 대해서도 정렬은 가능하다

print('열 정렬 - ')
print(np.sort(ary, axis = 0))
# 데이터 분석은 열을 기준으로 함
# print(ary)
print()
print('행 정렬 - ')
print(np.sort(ary, axis = 1))


열 정렬 - 
[[ 3 11  5  1]
 [ 8 15  8  1]
 [12 15 10  5]
 [16 16 15 15]]

행 정렬 - 
[[11 15 15 16]
 [ 1  5  8 15]
 [ 5 10 12 16]
 [ 1  3  8 15]]


- 만약, 정렬된 인덱스를 필요로 한다면?
- np.argsort()

In [324]:
ary = np.array([4,3,5,7])   # 1) sort => [3,4,5,7] 
print(ary)  

[4 3 5 7]


In [334]:
sortIdx = np.argsort(ary)  # 2) index의 값 0,1,2,3 부여 
print(sortIdx)   # 3) 출력 시 [1,0,2,3]
print()
print(ary[sortIdx])
print(ary[sortIdx][::-1])  # 역순 출력

[1 3 2 8 7 9 5 6 4 0]

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [338]:
ary = np.random.randint(1, 17, (4,4))
print(ary)

[[ 2 14 10  4]
 [13  5  4  4]
 [10 15 13  6]
 [ 5  4  8 11]]


In [341]:
# np.argsort(ary, axis = 1)  # 행(1)의 방향을 기준으로 index를 sorting 함
np.argsort(ary, axis = 0)  # 열(0)의 방향을 기준으로 index를 sorting 함

array([[0, 3, 1, 0],
       [3, 1, 3, 1],
       [2, 0, 0, 2],
       [1, 2, 2, 3]], dtype=int64)

- 배열에병합이 아닌 행, 열 추가하는 방법
- np.concatenate()
- 축의 방향을 설정하여 추가 axis = 
   

In [328]:
ary = np.array([[1,2,3],[4,5,6]])
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (2, 3)
ndim -  2
dtype -  int32


data - 
[[1 2 3]
 [4 5 6]]


In [329]:
rowAry = np.array([7,8,9])
# np.vstack([ary,rowAry])
print( np.concatenate( (ary, rowAry[ np.newaxis , : ]), axis = 0) )
print()
print( np.concatenate( (ary, rowAry.reshape(1,3)), axis = 0) )
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [331]:
# colAry= np.array([10,11,12])   # 행/열 수 맞지않아 오류 발생함

# print(ary)

colAry = np.array([10,11])

print( np.concatenate( (ary, colAry[ : , np.newaxis  ]) , axis = 1) )
print()
print( np.concatenate( (ary, colAry.reshape(2,1)) , axis = 1) )

[[ 1  2  3 10]
 [ 4  5  6 11]]

[[ 1  2  3 10]
 [ 4  5  6 11]]
